version: "3.9"

services:
    postgres-db:
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_PASSWORD: sample-password
        volumes:
            - /var/local/pgdata:/var/lib/postgresql/data
        ports:
            - 5433:5432

    first:
        build: firstbackend
        depends_on:
            - postgres-db
        ports:
            - 8081:8081

    second:
        build: secondbackend
        depends_on:
            - postgres-db
        ports:
            - 8082:8082

    api-gateway:
        image: devopsfaith/krakend:watch
        volumes:
            - ./api-gateway:/etc/krakend
        ports:
            - 8080:8080
        command: ["run", "-d", "-c", "/etc/krakend/krakend.json"]
