version: "3.9"

services:
    postgres-db:
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_PASSWORD: sample-password
        volumes:
            - /var/local/pgdata:/var/lib/postgresql/data

    first:
        build: firstbackend
        depends_on:
            - postgres-db
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/postgres
            OTEL_SERVICE_NAME: "first-backend"
            OTEL_EXPORTER_OTLP_ENDPOINT: "http://collector:4317"
            # Logs are disabled by default
            OTEL_LOGS_EXPORTER: "otlp"
        ports:
            - 8081:8081
        healthcheck:
            test: ["CMD", "curl", "-f", "http://first:8081/actuator/health"]
            interval: 10s
            timeout: 20s
            retries: 5
            start_period: 5s

    second:
        build: secondbackend
        depends_on:
            - postgres-db
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/postgres
            OTEL_SERVICE_NAME: "second-backend"
            OTEL_EXPORTER_OTLP_ENDPOINT: "http://collector:4317"
            # Logs are disabled by default
            OTEL_LOGS_EXPORTER: "otlp"
        ports:
            - 8082:8082
        healthcheck:
            test: ["CMD", "curl", "-f", "http://second:8082/actuator/health"]
            interval: 10s
            timeout: 20s
            retries: 5
            start_period: 5s

    api-gateway:
        image: devopsfaith/krakend:watch
        volumes:
            - ./api-gateway:/etc/krakend
        ports:
            - 8080:8080
        command: ["run", "-d", "-c", "/etc/krakend/krakend.json"]

    jaeger:
        image: jaegertracing/all-in-one:latest
        ports:
            - 16686:16686
            - 6831:6831/udp
            - 14268:14268
            - 14250:14250

    collector:
        image: otel/opentelemetry-collector-contrib:latest
        command: [ "--config=/etc/otel-collector-config.yaml" ]
        volumes:
            - ./config/otel-config.yaml:/etc/otel-collector-config.yaml
        expose:
            - 4317
            - 4318
        ports:
            - 1888:1888   # pprof extension
            - 13133:13133 # health_check extension
            - 4317:4317       # OTLP gRPC receiver
            - 4318:4318        # OTLP http reciever
            - 55670:55679 # zpages extension
        depends_on:
            - jaeger

    prometheus:
        image: prom/prometheus:latest
        volumes:
            - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
        ports:
            - 9090:9090

    grafana:
        image: grafana/grafana-oss:latest
        volumes:
            - ./config/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yaml
        environment:
            - GF_AUTH_ANONYMOUS_ENABLED=true
            - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
            - GF_AUTH_DISABLE_LOGIN_FORM=true
        ports:
            - 3000:3000
