version: "3.9"

services:
    first:
        build: firstbackend
        ports:
            - 8081:8081
    second:
        build: secondbackend
        ports:
            - 8082:8082
    api-gateway:
        image: devopsfaith/krakend:watch
        volumes:
            - ./api-gateway:/etc/krakend
        ports:
            - 8080:8080
        command: ["run", "-d", "-c", "/etc/krakend/krakend.json"]