receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  logging:
    logLevel: debug
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true

extensions:
  health_check:
  zpages:

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ jaeger ]
    logs:
      receivers: [otlp]
      exporters: [logging]
  extensions: [ health_check, zpages ]
