server:
  port: 8081
spring:
  datasource:
    username: postgres
    password: sample-password
  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoint:
    health:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus,health